### ISSUE TITLE
Style element is not supported

### ISSUE THREAD

**Issue by lukasgal** [bgalek/safe-svg#2]
Is there any reason why it's not supported <style> element? The content of  SVG_ELEMENTS is referenced to [https://developer.mozilla.org/en-US/docs/Web/SVG/Element](https://developer.mozilla.org/en-US/docs/Web/SVG/Element) but there is <style> element presented. I have problem with validating of the following svg icon. Would be possible to make a variable SVG_ELEMENT configurable? It's private variable so I cannot override it. Thank you.
```
<?xml version="1.0" encoding="utf-8"?>
  | <!-- Generator: Adobe Illustrator 23.0.3, SVG Export Plug-In . SVG Version: 6.00 Build 0)  -->
  | <svg version="1.1" id="Icons" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
  | viewBox="0 0 32 32" style="enable-background:new 0 0 32 32;" xml:space="preserve">
  | <style type="text/css">
  | .st0{fill:none;stroke:#000000;stroke-width:2;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:10;}
  | </style>
  | <path class="st0" d="M18,8h-4l-1.6-4.7C12.2,2.7,12.7,2,13.4,2h5.2c0.7,0,1.2,0.7,0.9,1.3L18,8z"/>
  | <polygon class="st0" points="21,26 16,31 11,26 14,8 18,8 "/>
  | <polyline class="st0" points="18,8 23,20 20.4,22.6 "/>
  | </svg>
 

```

**Comment by bgalek** [comment]
hi @lukasgal! Firs of all - thank you for pointing out this problem! 
Please give me a day or two to make some research and check out my notes on the issue - I'll be back with an answer!

**Comment by bgalek** [comment]
@lukasgal check out this PR :) #3

**Comment by lukasgal** [comment]
Thank you very much. Good work 👍

**Comment by bgalek** [comment]
@lukasgal I'll release new version today ;)

**Comment by lukasgal** [comment]
Hi @bgalek , it would be great. Thank you.

**Comment by bgalek** [comment]
1.1.0 released, should be available in few hours ;)
