### ISSUE TITLE
To support deprecated elements and some css properties 

### ISSUE THREAD

**Issue by Indhumathi-Syncron** [bgalek/safe-svg#30]
Hello Team,

We will be using svg validator to validate the file. But, we might also use svg files with some deprecated elements. So, whenever we get the files which contain SVG_ELEMENTS and SVG_ATTRIBUTES not defined in the safe-svg it is getting failed Eg: horiz-adv-x,missing-glyph. Also, few css properties are added as part of style attributes in the also not supporting. Eg : style = shape-rendering:geometricPrecision; text-rendering:geometricPrecision;

 So, if possible please implement to handle some deprecated tags & elements and css properties defined in style attribute. 
![Custom_image](https://user-images.githubusercontent.com/105271458/206463291-ce075a31-ab9f-42f2-a69e-858a7c3d3e97.svg)

**Comment by Indhumathi-Syncron** [comment]
@bgalek It is working as expected now. Thanks for the implementation. But, it's like we need to pass the deprecated elements to the code. Is their any possibility to handle the safe-svg implementation itself handles the deprecated items ?
If not, is their any possibility to get the list of deprecated svg elements and attributes ?

**Comment by bgalek** [comment]
Great!

You can get deprecated elements and attributes at mdn: https://developer.mozilla.org/en-US/docs/Web/SVG/Element#obsolete_and_deprecated_elements

**Comment by Indhumathi-Syncron** [comment]
Thanks!!!

The latest version of safe-svg 1.1.4 doesn't contain this changes. Could you please let us know when this changes will be released in maven repo ?

**Comment by bgalek** [comment]
1.1.6 is already released https://search.maven.org/artifact/com.github.bgalek.security.svg/safe-svg/1.1.6/jar

**Comment by Indhumathi-Syncron** [comment]
Hi @bgalek 
We have upgraded to latest jar.  But it is getting failed in the server with below error  after upgrading to 1.1.6
[error]        java.text.ParseException: inconsistent module descriptor file found in 'https://repo1.maven.org/maven2/commons-codec/commons-codec/20041127.091804/commons-codec-20041127.091804.pom': bad revision: expected='20041127.091804' found='1.3'; 
Could you please help us if you have any idea about this ?

**Comment by Indhumathi-Syncron** [comment]
Hi @bgalek ,
Could you please check the above reported issue

**Comment by bgalek** [comment]
@Indhumathi-Syncron check out 1.1.7, 1.1.6 actually had a dependency misalignment problem
