### ISSUE TITLE
When we pass broken images, it is being marked as valid file

### ISSUE THREAD

**Issue by Indhumathi-Syncron** [bgalek/safe-svg#31]
Hello @bgalek ,
When we pass the broken svg image, it is being marked as valid file instead of throwing PositiveValidationResult. 
Please have a look. 
![broken_image](https://user-images.githubusercontent.com/105271458/207530476-25b1829e-1269-4cc8-a821-2dcc0d710d1d.svg)

**Comment by bgalek** [comment]
@Indhumathi-Syncron take a look https://github.com/bgalek/safe-svg/pull/32
