### ISSUE TITLE
Default whitelist is invalidated with recent improvement

### ISSUE THREAD

**Issue by kiziltas** [bgalek/safe-svg#7]
I think with this change https://github.com/bgalek/safe-svg/pull/5/commits/12f3b33ca195450791b4376e0bda4dad6e116202 the default whitelist is invalidated and now the only style that is allowed is "enable-background". The `allowStyling()` method should have kept and extended with specific styles (because allowStyling() method unifies everything that's sent).

```
.allowStyling()
.allowStyling(CssSchema.withProperties(SVG_SPECIFIC_STYLES))
```

Bonus: It would be awesome if we could set a custom whitelist when composing `SvgSecurityValidator` :)

**Comment by bgalek** [comment]
Hi kiziltas!
I'll look at it ;) Of course, your'e welcom to create a PR :)

**Comment by bgalek** [comment]
@kiziltas could you provide an svg file example? :)

**Comment by bgalek** [comment]
@kiziltas You were right, version 1.1.1 is broken, I'm fixing the issue right away! I'll add some more tests to cover this case.

**Comment by bgalek** [comment]
@kiziltas 1.1.2 released https://github.com/bgalek/safe-svg/releases/tag/1.1.2

**Comment by kiziltas** [comment]
Thanks! (and apologize I missed your early input requests)

**Comment by bgalek** [comment]
no problem! :)
